# Generated by Django 5.2 on 2025-05-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_productgallery_options"),
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
