# Generated by Django 5.2 on 2025-04-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="variation_value",
            field=models.CharField(default=True, max_length=100),
        ),
    ]
