# Generated by Django 5.2 on 2025-04-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_variation_variation_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_value",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
