# Generated by Django 5.2 on 2025-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_orderproduct_color_remove_orderproduct_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="size",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
