# Generated by Django 5.2 on 2025-05-02 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_rename_variation_orderproduct_variations"),
        ("store", "0005_reviewrating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="variations",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="variation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.variation",
            ),
        ),
    ]
